# Generated by Django 3.2 on 2022-06-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='recipepost',
            name='updated_on',
        ),
    ]
