# Generated by Django 3.2 on 2022-06-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_recipe', '0002_auto_20220601_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='excerpt',
        ),
    ]
