# Generated by Django 3.2 on 2022-06-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='number_of_people',
            field=models.IntegerField(null=True),
        ),
    ]
