# Generated by Django 3.2 on 2022-06-22 09:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_timeslot_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='00', max_length=128, region=None),
        ),
    ]
