# Generated by Django 3.2 on 2022-06-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_foodmenu_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='course',
            field=models.CharField(choices=[('S', 'Starters'), ('M', 'Mains'), ('D', 'Desert')], max_length=1),
        ),
    ]
