# Generated by Django 3.2 on 2022-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_foodmenu_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='course',
            field=models.IntegerField(choices=[(0, 'Starters'), (1, 'Mains'), (2, 'Desert')]),
        ),
    ]
